[theme]
baseRadius = "0.5rem"
borderColor = "transparent"
[theme.sidebar]

[theme.light]
primaryColor = "#0083B8"  # 主色调，使用蓝色
backgroundColor = "#FFFFFF"  # 背景色
secondaryBackgroundColor = "#F0F2F6"  # 次要背景色
textColor = "#000000"  # 文本颜色纯黑
font = "sans serif"  # 字体
codeBackgroundColor = "#F9F9F9"  # 代码块背景色（深色，突出代码）

# 深色主题配置
[theme.dark]
primaryColor = "#ff4b4b"
backgroundColor = "#212121"
secondaryBackgroundColor = "#2F2F2F"
textColor = "#FFFFFF"
font = "sans serif"  # 字体
codeBackgroundColor = "#181818"  # 代码块背景色
